# Generated by Django 4.2.7 on 2023-11-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_prestamo_target_account_alter_prestamo_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='loan_type',
            field=models.CharField(choices=[('HIPOTECARIO', 'HIPOTECARIO'), ('PERSONAL', 'PERSONAL'), ('PRENDARIO', 'PRENDARIO')], default='PERSONAL', max_length=20),
        ),
    ]
