# Generated by Django 4.2.7 on 2023-11-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0002_delete_cuenta_delete_tiposdecuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
                ('account_type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeCuenta',
            fields=[
                ('account_type', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('option_number', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
