# Generated by Django 4.2.7 on 2023-11-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_cuenta_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TiposDeCuenta',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='account_type',
            field=models.CharField(choices=[('CAJA_AHORRO_PESOS', 'CAJA_AHORRO_PESOS'), ('CAJA_AHORRO_DOLARES', 'CAJA_AHORRO_DOLARES'), ('CUENTA_CORRIENTE_PESOS', 'CUENTA_CORRIENTE_PESOS'), ('CUENTA_CORRIENTE_DOLARES', 'CUENTA_CORRIENTE_DOLARES'), ('CUENTA_INVERSION', 'CUENTA_INVERSION')], default='CAJA_AHORRO_PESOS', max_length=25),
        ),
    ]
