# Generated by Django 4.2.7 on 2023-11-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('movimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuenta', models.IntegerField(blank=True, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('tipo_operacion', models.TextField(blank=True, null=True)),
                ('hora', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
