# Generated by Django 4.2.7 on 2023-11-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movimientos',
        ),
    ]
