# Generated by Django 4.2.7 on 2023-12-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_delete_tiposdecuenta_alter_cuenta_account_type'),
        ('movimientos', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='numero_cuenta',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='cuenta_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrantes', to='cuentas.cuenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='cuenta_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salientes', to='cuentas.cuenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='movimiento_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
