# Generated by Django 4.2.7 on 2023-12-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_delete_tiposdecuenta_alter_cuenta_account_type'),
        ('movimientos', '0004_remove_movimientos_hora_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movimientos',
            new_name='Movimiento',
        ),
    ]
