# Generated by Django 4.2.7 on 2023-11-27 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_initial'),
        ('tarjetas', '0002_remove_tarjeta_card_issuer_remove_tarjeta_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcasDeTarjeta',
            fields=[
                ('card_issuer', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('option_number', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_number', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('cvv', models.TextField(blank=True, db_column='CVV', null=True)),
                ('emision_date', models.TextField(blank=True, null=True)),
                ('expiry_date', models.TextField(blank=True, null=True)),
                ('card_type', models.TextField(blank=True, null=True)),
                ('card_issuer', models.ForeignKey(blank=True, db_column='card_issuer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tarjetas.marcasdetarjeta')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
        ),
    ]
