# Generated by Django 4.2.7 on 2023-12-01 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_delete_tiposdecuenta_alter_cuenta_account_type'),
        ('tarjetas', '0004_alter_tarjeta_card_issuer_alter_tarjeta_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='related_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_issuer',
            field=models.CharField(choices=[('VISA', 'VISA'), ('MASTER_CARD', 'MASTER_CARD'), ('AMERICAN_EXPRESS', 'AMERICAN_EXPRESS')], default='VISA', max_length=25),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_type',
            field=models.CharField(choices=[('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO')], default='DEBITO', max_length=25),
        ),
        migrations.DeleteModel(
            name='MarcasDeTarjeta',
        ),
    ]
