# Generated by Django 4.2.7 on 2023-12-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0005_rename_customer_tarjeta_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='card_number',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cvv',
            field=models.IntegerField(blank=True, db_column='CVV', null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='emision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
