# Generated by Django 4.2.7 on 2023-11-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_remove_tarjeta_card_issuer_remove_tarjeta_customer_and_more'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.DeleteModel(
            name='TiposDeCliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
