# Generated by Django 4.2.7 on 2023-11-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_remove_cliente_user_delete_tiposdecliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_surname', models.TextField()),
                ('customer_dni', models.TextField(db_column='customer_DNI')),
                ('dob', models.TextField(blank=True, null=True)),
                ('branch_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeCliente',
            fields=[
                ('client_type', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('option_number', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
