# Generated by Django 4.2.7 on 2023-11-28 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cutomer_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
