# Generated by Django 4.2.7 on 2023-11-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_branch_id_cliente_cutomer_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TiposDeCliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cutomer_type',
        ),
        migrations.AddField(
            model_name='cliente',
            name='customer_type',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Gold', 'Gold'), ('Black', 'Black')], default='Classic', max_length=20),
        ),
    ]
