# Generated by Django 4.2.7 on 2023-11-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_delete_tiposdecliente_remove_cliente_cutomer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
